feat(FFS-74) Implement ApplyEffects
Mythic-North-Games/FrostfallSaga pull request #28
Opened 2024-06-11 13:28 UTC by kebciSofiane

2024-06-11 13:56 UTC, Keirilaz approved these changes

2024-06-11 13:59 UTC, Keirilaz requested changes

2024-06-11 13:59 UTC, Keirilaz commented on Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs
Applique au pv et non a la résistance

2024-06-11 15:31 UTC, ASparton commented on Assets/Code/Scripts/Fight/Fighter/FighterStats.cs
> +        public int fireResistance;
Il vaut mieux avoir un Dict<EMagicalElement, int> pour éviter les switch case à chaque fois

2024-06-18 08:08 UTC, ASparton approved these changes

2024-06-18 08:23 UTC, merged