Ffs 227 applying the statuses
Mythic-North-Games/FrostfallSaga pull request #96
Opened 2024-09-26 15:00 UTC by kebciSofiane

2024-09-26 15:06 UTC, Alexis-Guyon-EP commented on Assets/Code/Scripts/Fight/StatusEffects/StatusEffect/ParalysisStatus.cs
> +            animationStateName = "Bleed";
Animation d'hémorragie pour de la paralysie ?

2024-09-26 15:08 UTC, Alexis-Guyon-EP commented on Assets/Code/Scripts/Fight/StatusEffects/StatusEffectManager.cs
> +            var tempStatusEffects = new Dictionary<StatusEffect, (bool isActive, int duration)>();
J'suis pas fan du "var" si t'as des explications sur pourquoi le var je suis preneur

2024-09-26 15:10 UTC, Alexis-Guyon-EP commented on Assets/Code/Scripts/Fight/Fighter/Fighter.cs
> +                    _stats.strength -= statReduction;
J'en ai aucune idée sur ça mais est-ce que la stats affecté peut être négatif ?

2024-09-26 15:12 UTC, Alexis-Guyon-EP reviewed
Il faut retirer le code en commentaire qui n'est pas utilisé
Je ne sais pas si les stats que tu decrease supporte le négatif (ex: 0 d'initiative -100 = -100 ou = 0)
L'animation de paralysie est la même que celle de l'hémorragie ? peut être qu'on a pas d'animation de paralysie

2024-09-26 15:28 UTC, Alexis-Guyon-EP approved these changes

2024-09-27 09:41 UTC, ASparton requested changes

2024-09-27 09:41 UTC, ASparton commented on Assets/Tests/Tests.asmdef
Why is there a new test folder here? I don't think we need it

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterStatusAbilitiesTests.cs
> +            var isActive = statusEffects.ContainsKey(weaknessStatus);
```suggestion
            Assert.IsFalse(statusEffects.ContainsKey(weaknessStatus));
```

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterStatusAbilitiesTests.cs
> +            var paralysisStatus = new ParalysisStatus();
Avoid using var and use real type instead for better readability

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterStatusAbilitiesTests.cs
> +    public class FighterStatusAbilitiesTests
Good job for the tests ! A pleasure to see that 👍

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
> +using FrostfallSaga.Fight.StatusEffects;
```suggestion
```

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/StatusEffects/StatusEffect/StatusEffect.cs
> +        public abstract void ApplyEffect(Fighter fighter);
```suggestion
        public abstract void ApplyStatus(Fighter fighter);
```

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/StatusEffects/StatusEffect/WeaknessStatus.cs
> +        public int getstrengthReduction()
```suggestion
        public int GetstrengthReduction()
```

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/Fighter/Fighter.cs
> +        public string FighterName { get; private set; }
Delete this

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/Fighter/Fighter.cs
> +            statusManager = gameObject.AddComponent<StatusEffectManager>();
Add to prefab instead

2024-09-27 09:41 UTC, ASparton commented on Assets/Code/Scripts/Fight/Fighter/Fighter.cs
> +            // PlayAnimationIfAny(animationStateName);
```suggestion
            PlayAnimationIfAny(animationStateName);
```

2024-10-11 13:03 UTC, merged